[package]
name = "booklibrs"
version = "0.1.4"
authors = ["Paranid5 <dinaraparanid@gmail.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "Book libarary project including giveaway operations and gui interface. Beta version"
homepage = "https://github.com/dinaraparanid/Library_rs"
documentation = "https://docs.rs/binartree/0.1.4/booklibrs/"

[dependencies]
chrono = "0.4.19"
fltk = "0.13.9"
yaml-rust = "0.4.5"