[package]
name = "librs"
version = "0.1.0"
authors = ["Paranid5 <dinaraparanid@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
fltk = "0.12.5"